### ISSUE TITLE
France wind turbines

### ISSUE THREAD

**Issue by jthomasmock** [rfordatascience/tidytuesday#16]
https://opendata-renewables.engie.com/explore/dataset/la-haute-borne-data-2013-2016/

**Comment by AndreaPi** [comment]
This is mighty interesting. Has anyone in the community analyzed these data yet?

**Comment by jthomasmock** [comment]
Not that I've seen - I was just googling for energy use and found that open portal

**Comment by AndreaPi** [comment]
Nice, nice! I have a long holiday this week, but I may a stab at it in one or two weeks. I'll randomly check the #tidytuesdays channel to see if someone else wants to work on it.

**Comment by AndreaPi** [comment]
Ok - I decided, I will analyze the dataset. But, I will likely write a long EDA in a RMarkdown document, rather than a single graph. Would it be still interesting for you if I shared the link to the GitHub repo? Shall I wait until when you choose to use the data for a #tidytuesdays? I've got my hands full with a lot of other stuff, so for what it concerns me there's no hurry - even if you decide to wait 3 or 4 Tuesdays before using it, fine for me 😀
