### ISSUE TITLE
rKenya census

### ISSUE THREAD

**Issue by jthomasmock** [rfordatascience/tidytuesday#297]
https://github.com/Shelmith-Kariuki/rKenyaCensus

**Comment by nsgrantham** [comment]
Hi Tom,

If you copy-and-paste `remotes::install_github(“Shelmith-Kariuki/rKenyaCensus”)` you get `Error: unexpected input in "remotes::install_github(�"` because R doesn't recognized the slanted quote characters.

Replace the line with `remotes::install_github("Shelmith-Kariuki/rKenyaCensus")` and it will work.
